// <auto-generated />
namespace CookBook.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Category_Recipes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_Recipes));
        
        string IMigrationMetadata.Id
        {
            get { return "202306131948126_Category_Recipes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
